language: node_js
node_js: lts/*

install:
  - npm install

script:
  - npm run build
  - cp ./dist/vue-qrcode-reader.js ./dist/vue-qrcode-reader.common.js
  - cp ./dist/vue-qrcode-reader.umd.js ./dist/vue-qrcode-reader.browser.js

cache: npm

deploy:
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|alpha)$
    script:
      - npx semantic-release
