language: node_js
node_js: lts/*

install:
  - npm install

script:
  - npm run build

cache: npm

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script:
      - npx semantic-release
  - provider: script
    skip_cleanup: true
    on:
      branch: alpha
    script:
      - npx semantic-release
